export type CodeEditorLanguagesUnion = keyof typeof CodeEditorLanguages
export const CodeEditorLanguagesDisplayName: {
  [key in CodeEditorLanguagesUnion]: string
} = {
  'C': 'C',
  'CPP': 'C++',
  'CSHARP': 'C#',
  'CSS': 'CSS',
  'CRYSTAL': 'Crystal',
  'DART': 'Dart',
  'ELM': 'Elm',
  'GO': 'Go',
  'HASKELL': 'Haskell',
  'HTML': 'HTML',
  'JAVA': 'Java',
  'JAVASCRIPT': 'JavaScript',
  'JSON': 'JSON',
  'JSX': 'JSX',
  'KOTLIN': 'Kotlin',
  'LUA': 'Lua',
  'MARKDOWN': 'MarkDown',
  'OBJECTIVE_C': 'Objective-C',
  'PHP': 'PHP',
  'PROPERTIES': 'Properties',
  'PYTHON': 'Python',
  'R': 'R',
  'RUBY': 'Ruby',
  'RUST': 'Rust',
  'SHELL': 'Shell',
  'SQL': 'SQL',
  'SWIFT': 'Swift',
  'SCALA': 'Scala',
  'TSX': 'TSX',
  'TYPESCRIPT': 'TypeScript',
  'TOML': 'TOML',
  'WEB_ASSEMBLY': 'Web Assembly',
  'XML': 'XML',
  'YAML': 'YAML',
}
